#!/usr/bin/env bash
ZSH=$HOME/.oh-my-zsh
ZSH_CUSTOM=$ZSH/custom

if [ ! -d  "${ZSH}" ]; then
  echo -e "==> installing oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# ##########################
# #	      PLUGINS	                              #
# ##########################
if [ ! -d "${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting" ]; then
  echo -e "==> cloning syntax highlighting "
  git clone git@github.com:zsh-users/zsh-syntax-highlighting.git "${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting"
fi


if [ ! -d "${ZSH_CUSTOM}/plugins/zsh-autosuggestions" ]; then
  echo -e "==> cloning zsh-autosuggestions "
  git clone git@github.com:zsh-users/zsh-autosuggestions "${ZSH_CUSTOM}/plugins/zsh-autosuggestions"
fi
