#!/usr/bin/env bash

export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$ZSH/custom

if [ ! -d  "${ZSH}" ]; then
  echo -e "==> installing oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  rm ~/.zshrc
fi

# #  Theme
if [ ! -d "${ZSH_CUSTOM}/themes/pure" ]; then
  echo -e "==> cloning pure theme"
  git clone https://github.com/sindresorhus/pure.git "${ZSH_CUSTOM}/themes/pure"
fi

# ##########################
# #	      PLUGINS	                              #
# ##########################
if [ ! -d "${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting" ]; then
  echo -e "==> cloning syntax highlighting "
  git clone git://github.com/zsh-users/zsh-syntax-highlighting.git "${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting"
fi


if [ ! -d "${ZSH_CUSTOM}/plugins/zsh-autosuggestions" ]; then
  echo -e "==> cloning zsh-autosuggestions "
  git clone git://github.com/zsh-users/zsh-autosuggestions "${ZSH_CUSTOM}/plugins/zsh-autosuggestions"
fi
